### ISSUE TITLE
[wav2ema] RuntimeError: input.size(-1) must be equal to input_size. Expected 1024, got 13

### ISSUE THREAD

**Issue by cdaube** [articulatory/articulatory#2]
Hi there,
I am trying to use predict_ema.py as described in the readme.

I get the following error for a stereo wav (same for a mono wav) as input:

Traceback (most recent call last):
  File "/analyse/cdhome/articulatory/egs/ema/voc1/local/predict_ema.py", line 104, in <module>
    pred = inversion_model.inference(feat, normalize_before=False)
  File "/analyse/cdhome/articulatory/articulatory/models/pytorch_models.py", line 104, in inference
    c = self.forward(c.unsqueeze(0).transpose(1, 2), ar=ar, spk=spk)
  File "/analyse/cdhome/articulatory/articulatory/models/pytorch_models.py", line 63, in forward
    output, hn = self.gru1(mels)
  File "/home/chrisd/anaconda3/envs/articulatory/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chrisd/anaconda3/envs/articulatory/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 996, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "/home/chrisd/anaconda3/envs/articulatory/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 253, in check_forward_args
    self.check_input(input, batch_sizes)
  File "/home/chrisd/anaconda3/envs/articulatory/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 218, in check_input
    raise RuntimeError(
RuntimeError: input.size(-1) must be equal to input_size. Expected 1024, got 13

**Comment by cdaube** [comment]
EDIT: I think I got it to work. The problem was that the script was anticipating hubert features, but got mfcc features.

The downloaded weights should probably ideally be stored in a folder called /exp/, and then one should use 
exp/hprc_no_m1f2_h2emaph_gru_joint_nogan
for wav2ema
as well as

exp/mngu0_e2w_hifi
for 13dim wav2ema
and 

exp/mngu0_ema2w
for 12dim wav2ema,
since the code looks for parts of the folders where the weights are stored
(e.g. "if '_h2' in exp_id:" in line 40 of predict_ema.py).
